---
apiVersion: v1
kind: Pod
metadata:
  name: redis-boot
  namespace: redis
spec:
  containers:
  - image: zdq0394/redis-cluster-boot:1.2
    name: redis-boot
    env:
      - name: CLUSTER_DOMAIN
        value: "cluster.local"
      - name: HEADLESS_SERVICE_NAME
        value: "redis-service"
      - name: NAMESPACE
        value: "redis"
      - name: STATEFULSET_NAME
        value: "redis-app"
    command:
      - "/boot/boot.sh"
  restartPolicy: "Never"
