---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: docker-registry.saicstack.com/kubernetes/grafana:5.1.1
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SERVER_ROOT_URL
          value: /
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_ALERTING_ENABLED
          value: "true"
        - name: GF_ALERTING_EXECUTE_ALERTS
          value: "true"
        - name: GF_PATHS_PROVISIONING
          value: "/data/provisioning/"
        volumeMounts:
        - name: grafana-ds-config
          mountPath: /data/provisioning/datasources
        - name: grafana-dashboard-config
          mountPath: /data/provisioning/dashboards
        - name: gfdashboard-k8s-cluster-health
          mountPath: /data/dashboards/k8s-cluster-health
        - name: gfdashboard-k8s-cluster-monitoring
          mountPath: /data/dashboards/k8s-cluster-monitoring
        - name: gfdashboard-docker-host
          mountPath: /data/dashboards/gfdashboard-docker-host
      volumes:
        - name: grafana-ds-config
          configMap:
            name: grafana-ds-config
        - name: grafana-dashboard-config
          configMap:
            name: grafana-dashboard-config
        - name: gfdashboard-k8s-cluster-health
          configMap:
            name: gfdashboard-k8s-cluster-health
        - name: gfdashboard-k8s-cluster-monitoring
          configMap:
            name: gfdashboard-k8s-cluster-monitoring
        - name: gfdashboard-docker-host
          configMap:
            name: gfdashboard-docker-host
        

