---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-config
  namespace: monitoring
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090