apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ha-configmap
  namespace: redis
  labels:
    app: redis-ha
data:
  redis.conf: |
    dir "/data"
    requirepass replace-default-auth
    masterauth replace-default-auth

  sentinel.conf: |
    dir "/data"
    sentinel auth-pass mymaster replace-default-auth

  init.sh: |
    MASTER=
    REDIS_CONF=/data/conf/redis.conf
    SENTINEL_CONF=/data/conf/sentinel.conf
    
    set -e
    function sentinel_update(){
        echo "Updating sentinel config"
        sed -i "1s/^/sentinel monitor mymaster $1 6379 2 \n/" $SENTINEL_CONF
    }

    function redis_update(){
        echo "Updating redis config"
        echo "slaveof $1 6379" >> $REDIS_CONF
    }

    function setup_defaults(){
        echo "Setting up defaults"
        if [[ "$HOSTNAME" == "redis-ha-0" ]]; then
            echo "Setting this pod as the default master"
            sed -i "s/^.*slaveof.*//" $REDIS_CONF
            sentinel_update "$POD_IP"
        else
            echo "Setting default slave config.."
            echo "slaveof redis-ha-0.redis-ha 6379" >> $REDIS_CONF
            sentinel_update "redis-ha-0.redis-ha"
            redis_update "redis-ha-0.redis-ha"
        fi
    }

    function find_master(){
        echo "Attempting to find master"
        if [[ ! `redis-cli -h $MASTER -a $AUTH ping` ]]; then
           echo "Can't ping master, attempting to force failover"
           if redis-cli -h redis-ha -p 26379 sentinel failover mymaster | grep -q 'NOGOODSLAVE' ; then 
               setup_defaults
               return 0
           fi
           sleep 10
           MASTER=`redis-cli -h redis-ha -p 26379 sentinel get-master-addr-by-name mymaster | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
           if [[ "$MASTER" ]]; then
               sentinel_update $MASTER
               redis_update $MASTER
           else
              echo "Could not failover, exiting..."
              exit 1
           fi
        else
            echo "Found reachable master, updating config"
            sentinel_update $MASTER
            redis_update $MASTER
        fi
    }

    mkdir -p /data/conf/
    echo "Initializing config.."

    cp /readonly-config/redis.conf $REDIS_CONF
    cp /readonly-config/sentinel.conf $SENTINEL_CONF

    if [[ "$MASTER" ]]; then
        find_master
    else
        setup_defaults
    fi
    if [[ "$AUTH" ]]; then
        echo "Setting auth values"
        sed -i "s/replace-default-auth/$AUTH/" $REDIS_CONF $SENTINEL_CONF
    fi

    echo "Ready..."

