apiVersion: v1
kind: Service
metadata:
  name: redis-ha
  namespace: redis
  labels:
    app: redis-ha
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app: redis-ha
