apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-ha
spec:
  selector:
    matchLabels:
      app: redis-ha
  serviceName: redis-ha
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-ha
    spec:
      initContainers:
      - name: config-init
        image: registry.docker-cn.com/library/redis:5.0.1
        command:
        - bash
        args:
        - /readonly-config/init.sh
        env:
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: redis-ha
              key: auth
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /readonly-config
          readOnly: true
        - name: data
          mountPath: /data
      containers:
      - name: redis
        image: registry.docker-cn.com/library/redis:5.0.1
        command:
        - redis-server
        args:
        - /data/conf/redis.conf
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: 1000Mi
            cpu: 500m
          limits:
            memory: 2000Mi
        ports:
        - name: redis
          containerPort: 2379
        volumeMounts:
        - mountPath: /data
          name: data
      - name: sentinel
        image: registry.docker-cn.com/library/redis:5.0.1
        command:
          - redis-sentinel
        args:
          - /data/conf/sentinel.conf
        livenessProbe:
          exec:
            command: ["redis-cli", "-p", "26379", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["redis-cli", "-p", "26379", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 200Mi
        ports:
          - name: sentinel
            containerPort: 26379
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: config
        configMap:
          name: redis-ha-configmap
      - name: data
        emptyDir: {}
