---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: mongo-pv
  labels:
    type: mongopv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo_data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: mongopv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.2.16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - mountPath: /etc/localtime
          name: tz-config
          readOnly: true
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    name: mongo-svc
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    name: mongo