---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      nodeSelector:
        monitor: "true"
      containers:
      - image: prometheus:v1.7.1
        name: prometheus
        args: ["-alertmanager.url=http://alertmanager:9093", "-config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: alert-target-rule-cm
          mountPath: /etc/alert/rules/target
        - name: alert-etcd-rule-cm
          mountPath: /etc/alert/rules/etcd
        - name: alert-node-rule-cm
          mountPath: /etc/alert/rules/node
        - name: alert-apiserver-rule-cm
          mountPath: /etc/alert/rules/apiserver
      volumes:
        - name: prometheus-config
          configMap:
            name: prom-config
        - name: alert-target-rule-cm
          configMap:
            name: alert-target-rule-cm
        - name: alert-etcd-rule-cm
          configMap:
            name: alert-etcd-rule-cm
        - name: alert-node-rule-cm
          configMap:
            name: alert-node-rule-cm
        - name: alert-apiserver-rule-cm
          configMap:
            name: alert-apiserver-rule-cm
