---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdisk
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-disks
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  ports:
  - name: graphite
    port: 2003
    targetPort: 2003
  - name: http
    port: 8086
    targetPort: 8086
  type: ClusterIP
  selector:
    app: influxdb
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:1.7
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
          - containerPort: 8086
            name: http
            protocol: TCP
          - containerPort: 8083
            name: admin
            protocol: TCP
          - containerPort: 2003
            protocol: TCP
            name: graphite
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: INFLUXDB_DB
            value: JMXData
          - name: INFLUXDB_ADMIN_USER
            value: JMXAdmin
          - name: INFLUXDB_ADMIN_PASSWORD
            value: JMXAdmin
          - name: INFLUXDB_GRAPHITE_ENABLED
            value: "true"
        volumeMounts:
          - mountPath: "/var/lib/influxdb"
            name: influxdata
      volumes:
        - name: influxdata
          persistentVolumeClaim:
            claimName: influxdisk
