apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover
  namespace: redis
spec:
  hardAntiAffinity: true                    # Optional. Value by default. If true, the pods will not be scheduled on the same node.
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: middleware/redis
          operator: In
          values:
          - "true"
  sentinel:
    replicas: 3                              # Optional. 3 by default, can be set higher.
    resources:                               # Optional. If not set, it won't be defined on created resources.
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig: []                         # Optional. Empty by default.
  redis:
    replicas: 3                              # Optional. 3 by default, can be set higher.
    image: redis  # Optional. "redis" by default.
    version: 5.0.1                      # Optional. "3.2-alpine" by default.
    resources:                               # Optional. If not set, it won't be defined on created resources
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    exporter: false                          # Optional. False by default. Adds a redis-exporter container to export metrics.
    exporterImage: oliver006/redis_exporter  # Optional. oliver006/redis_exporter by default.
    exporterVersion: v0.11.3                 # Optional. v0.11.3 by default.
    disableExporterProbes: false             # Optional. False by default. Disables the readiness and liveness probes for the exporter.
    storage:
      emptyDir: {}                           # Optional. emptyDir by default.
    customConfig: []                         # Optional. Empty by default.
