---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    name: grafana
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    nodePort: 10300
    targetPort: 3000
  type: NodePort
  selector:
    name: grafana
  sessionAffinity: ClientIP