---
apiVersion: v1
kind: Service
metadata:
  name: km-cs
  labels:
    name: kafka-manager
spec:
  type: NodePort
  ports:
    - name: kafka-manager
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 10111
  selector:
    name: kafka-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-manager
  template:
    metadata:
      labels:
        name: kafka-manager
    spec:
      restartPolicy: Always
      containers:
      - image: zdq0394/kafka-manager
        name: kafka-manager
        env:
        - name: ZK_HOSTS
          value : "zk-cs.default.svc.cluster.local"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
