---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - image: docker-registry.saicstack.com/prom/prometheus:v1.7.1
        name: prometheus
        args: ["-alertmanager.url=http://alertmanager:9093", "-config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: alert-rule-config
          mountPath: /etc/rules
      volumes:
        - name: prometheus-config
          configMap:
            name: prom-config
        - name: alert-rule-config
          configMap:
            name: alert-rule-config
