apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rule-config
  namespace: monitoring
data:
  alert.rules: |
    # Alert for any instance that is unreachable for >5 minutes.
    ALERT InstanceDown
      IF up == 0
      FOR 3m
      LABELS { severity = "high" }
      ANNOTATIONS {
        summary = "Instance {{ $labels.instance }} down",
        description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 3 minutes.",
      }
