---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    name: prometheus
spec:
  ports:
    # the port that this service should serve on
  - port: 9090
    nodePort: 10090
    targetPort: 9090
  type: NodePort
  selector:
    name: prometheus
  sessionAffinity: ClientIP
