apiVersion: v1
kind: Service
metadata:
  name: myconsul-nodeport
  namespace: dq
  labels:
    app: myconsul
spec:
  type: NodePort
  ports:
  - name: consul
    port: 8500
    targetPort: 8500
    nodePort: 18500
  selector:
    app: myconsul
    appCluster: myconsul