---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo 
  namespace: dq 

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-reader
  namespace: dq 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-reader-bind
  namespace: dq
subjects:
- kind: ServiceAccount
  name: mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongo-reader