apiVersion: v1
kind: ConfigMap
metadata:
  name: am-config
  namespace: monitoring
data:
  alertmanager.yml: |
      global:
        smtp_smarthost: 'smtp.163.com:25'
        smtp_from: 'zdq123.hn@163.com'
        smtp_auth_username: 'zdq123.hn@163.com'
        smtp_auth_password: '********'
        resolve_timeout: 1m
        smtp_require_tls: false

      route:
        group_by: ['alertname']
        group_wait: 5s
        group_interval: 10s
        repeat_interval: 1h 
        receiver: team-X-mails

      receivers:
      - name: 'team-X-mails'
        email_configs:
        - to: 'zhangdongqi@qiniu.com'