---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    name: alertmanager
spec:
  ports:
    # the port that this service should serve on
  - port: 9093
    nodePort: 10093
    targetPort: 9093
  type: NodePort
  selector:
    name: alertmanager
  sessionAffinity: ClientIP
